// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PunchSystem.Data;

#nullable disable

namespace PunchSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250511151534_InitWithIntIds")]
    partial class InitWithIntIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoinconUtilisation", b =>
                {
                    b.Property<int>("PoinconsId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisationsId")
                        .HasColumnType("int");

                    b.HasKey("PoinconsId", "UtilisationsId");

                    b.HasIndex("UtilisationsId");

                    b.ToTable("PoinconUtilisation");
                });

            modelBuilder.Entity("PunchSystem.Models.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("PunchSystem.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisationId");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("PunchSystem.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("PunchSystem.Models.Poincon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChAdm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clavetage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeGMAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateFabrication")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMiseEnService")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Diametre")
                        .HasColumnType("float");

                    b.Property<string>("EmplacementReception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FicheTechniqueUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fournisseur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GravureInf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GravureSup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Largeur")
                        .HasColumnType("float");

                    b.Property<double?>("Longueur")
                        .HasColumnType("float");

                    b.Property<string>("Marque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefInf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefSup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secabilite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Poincons");
                });

            modelBuilder.Entity("PunchSystem.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PunchSystem.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("PunchSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PunchSystem.Models.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("PunchSystem.Models.Utilisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compresseuse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUtilisation")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmplacementRetour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreComprimés")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilisations");
                });

            modelBuilder.Entity("UserUtilisation", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisationsId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "UtilisationsId");

                    b.HasIndex("UtilisationsId");

                    b.ToTable("UserUtilisation");
                });

            modelBuilder.Entity("PoinconUtilisation", b =>
                {
                    b.HasOne("PunchSystem.Models.Poincon", null)
                        .WithMany()
                        .HasForeignKey("PoinconsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PunchSystem.Models.Utilisation", null)
                        .WithMany()
                        .HasForeignKey("UtilisationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PunchSystem.Models.LoginHistory", b =>
                {
                    b.HasOne("PunchSystem.Models.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PunchSystem.Models.Lot", b =>
                {
                    b.HasOne("PunchSystem.Models.Utilisation", "Utilisation")
                        .WithMany("Lots")
                        .HasForeignKey("UtilisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisation");
                });

            modelBuilder.Entity("PunchSystem.Models.RolePermission", b =>
                {
                    b.HasOne("PunchSystem.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PunchSystem.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PunchSystem.Models.User", b =>
                {
                    b.HasOne("PunchSystem.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PunchSystem.Models.UserPermission", b =>
                {
                    b.HasOne("PunchSystem.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PunchSystem.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserUtilisation", b =>
                {
                    b.HasOne("PunchSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PunchSystem.Models.Utilisation", null)
                        .WithMany()
                        .HasForeignKey("UtilisationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PunchSystem.Models.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("PunchSystem.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PunchSystem.Models.User", b =>
                {
                    b.Navigation("LoginHistories");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("PunchSystem.Models.Utilisation", b =>
                {
                    b.Navigation("Lots");
                });
#pragma warning restore 612, 618
        }
    }
}
